### ISSUE TITLE
Option keypress isn't recognized in the key binds

### ISSUE THREAD

**Issue by ghost** [seathasky/FF14-MAC_ModSupport#10]
I'm used to using that key as a modifier for my Hotbar. Using control isn't a solution as it is too far away from my thumb. I guess that the behavior of the option key was customized by CodeWeavers in the official client of FFXIV.

**Comment by seathasky** [comment]
Try karabiner elements https://karabiner-elements.pqrs.org/

**Comment by realAbitbol** [comment]
I can confirm Karabiner Elements solves the problem.
I suggest using a remap of "left option" to "left command" because, surprisingly, command seems to equal alt inside the crossover bottle
<img width="795" alt="image" src="https://user-images.githubusercontent.com/73762857/140455272-082680ca-49cb-4fee-a712-cfd98168263b.png">
