### ISSUE TITLE
Can't install XIVLauncher

### ISSUE THREAD

**Issue by ahjsrhj** [seathasky/FF14-MAC_ModSupport#24]
![image](https://user-images.githubusercontent.com/8666955/142458520-f5b1a542-8990-4582-babe-ee128c1b9686.png)
The last step could not be completed
My OS info is：
MacOS 12.0.1 with m1
CrossOver 21.0 21.1  all like this

**Comment by seathasky** [comment]
The problem may be related to your networking or failed dependency installation. This does happen sometimes due to weird issues with Crossover's servers. 

**Please verify that all .NET dependencies were installed during crosstie installation.**

I just tested myself and there is nothing wrong with the installer, 
I recorded myself installing and it runs perfectly, click the gif to see full video

[![QUICK TEST](https://i.imgur.com/TA68HdX.gif)](https://www.youtube.com/watch?v=mV-_DEtZVuo)

**Comment by ahjsrhj** [comment]
.NET dependencies Installation is very slow，but all is success, and the last step XIV Launcher install window can't show。
I will change my proxy to try again.
thanks for your help

**Comment by seathasky** [comment]
Hopefully you can get it running!
