### ISSUE TITLE
Korean FFXIV client

### ISSUE THREAD

**Issue by ghost** [seathasky/FF14-MAC_ModSupport#32]
The Korean FFXIV has a separate client and setup.exe.  It is mostly the same as the original, but is locked to the local servers.  How do I get this repo to work with that client, particularly the custom XIVLauncher.exe?  Thanks.

**Comment by seathasky** [comment]
Unfortunately, the Korean client is completely out of reach for most users outside of Korea due to the restrictions used in that country. Our team only have access to North America, Europe and Australian clients. 

The Korean copy of the game also has a separate membership due to it being published by Actoz Soft. It would require us to have a Korean Social security and phone # which is basically impossible (legally) for anyone outside Korea. 

As much as I want to help you figure out your situation, I dont think it will be possible at this time. 

As far as XIVlauncher goes, I cant speak for that development team if it does or does not work with Actoz Soft's Korean version of the game, that is something you may want to ask here: https://github.com/goatcorp/FFXIVQuickLauncher or over at their discord: https://discord.com/invite/3NMcUV5

If the devs at XIVLauncher say it's usable on the Korean client, come back and reply and i'll recommend some steps to get it working for you.

Alternatively, you may be able to use the Japanese client in your country. You would require a vpn connected to Japan though... but the Japanese client of the game is the same as NA/EU and will work with XIVLauncher. 

Reading this older reddit post here, it seems that Korean players prefer the international servers anyways:
https://www.reddit.com/r/ffxiv/comments/8y3waw/us_player_trying_to_play_on_korean_server/

Best of luck!

**Comment by ghost** [comment]
Thank you for the fast response.  I have the Korean Resident ID, phone number, have a membership with Actoz, and am aware it is behind in patches.  You do not need a VPN to play on Japan's server.

But, I would like to play locally for the reasons I mentioned in my message.  I have posted the launcher issue here: https://github.com/goatcorp/FFXIVQuickLauncher/issues/592

Thanks again

**Comment by seathasky** [comment]
I understand, making Korean friends is important and in your email you mentioned language exchange which makes sense.

If XIVLauncher implements support for your Korean client, I will do my best to assist you in getting it running in Crossover etc. Outside of that, my hands are tied.
