### ISSUE TITLE
Stuttering on 13" Macbook M1 Pro

### ISSUE THREAD

**Issue by kayzerkan** [seathasky/FF14-MAC_ModSupport#39]
hello there!

first off, thanks for all the hard work in putting this together! seems like you guys spend more time and thought in this, than square enix themselves for the mac client :D

Now onto my issue. I basically have the problems as described by russel here #33. 

The game runs stable at around 70 fps, but I get sporadic stutters. Game dips to 30 fps for a second. Even the audio gets interupted. It's way more frequent for me tho. Like once every minute but it's hard to say exactly. I tried the solutions which where posted in that issue but it didn't help.

Any ideas what else I did wrong? If I use the "native" mac client, I don't get the stutters (while ofc having less fps overall). I am using a Macbook M1 Pro with 8 GBs and Big Sur 11.4

Thanks in advance!

**Comment by seathasky** [comment]
It sounds like shader cache is loading. This is normal and overtime, should usually work itself out completely. 

What version of moltenvk are you using?

**Comment by kayzerkan** [comment]
<img width="573" alt="Bildschirmfoto 2021-11-29 um 06 12 13" src="https://user-images.githubusercontent.com/29822268/143812460-aae5db4f-6350-424b-b03c-586fe202d75e.png">

The one specified in option 3

**Comment by seathasky** [comment]
Hey Kay, you could always try installing DXVK and Moltenvk into the native launcher. If this is something you are interested in, let me know, I can guide you in the process.

**Comment by kayzerkan** [comment]
Do you think I can't fix the stuttering with your crossover tue and the custom launcher?

Would using DXVK and MoltenVk boost peformance with the native launcher? I have to say I like the fps boost, I got from this guide. So I'd like to keep it :D

**Comment by seathasky** [comment]
Our project here has always been about performance first. The reason we recommend using Crossover 21 is because it includes the latest wine updates. The native launcher does not.

I cant speak for everyone, but I personally have tested DXVK/MVK updates on the Native Launcher and have seen fps improvement, i'm also on supported hardware though, so there is a difference. 

Bottomline, you wont get the full performance treatment like you would with CX21.

M1 users have it harder than Intel users though. Not only are you on unsupported hardware for the game (M1 CPU), you have double amount of translation to deal with Rosetta and Wine.
Square Enix does not support the M1 at all so this makes things even more difficult.
![Screen Shot 2021-11-29 at 11 33 46 AM](https://user-images.githubusercontent.com/17598024/143906561-305e4a4e-5533-4c7a-99e3-e4f05741a3a2.png)

Let me know what you want to try and I can do my best to help.

**Comment by kayzerkan** [comment]
Yea the lack of M1 support bums me up aswell. Once apple removes Rosetta2, M1 players are screwed. Even Blizzard has native M1 support for WoW. All the peformance issues would be solved.
Thanks a lot for your help and time! I guess for now I'll just stick to the official Launcher. I don't want to risk any downloads etc before Endwalker releases
Thanks again and see you on the moon ;)

**Comment by seathasky** [comment]
XIVLauncher made a statement about EW just yesterday. 

![Screen Shot 2021-11-29 at 3 22 34 PM](https://user-images.githubusercontent.com/17598024/143937500-ccaab296-9455-43ca-96a3-2e55af3b9fef.png)

It's always wise to keep the official launcher around anyways, just in-case.
